### ISSUE TITLE
Falta la propiedad Bases Reguladoras

### ISSUE THREAD

**Issue by jcballesteros** [opencitydata/sector-publico-subvenciones-ayudas#17]
Esta propiedad es una URL que apunta a un recurso que contiene la información de la subvención.

En el sistema nacional de subvenciones este campo se llama "bases reguladoras".

**Comment by ocorcho** [comment]
Propiedad añadida en el commit 08a5f23e998ca16339a0c9df6b1cdef3f24f8db4
