### ISSUE TITLE
Falta la propiedad essubv:tipoInstrumento 

### ISSUE THREAD

**Issue by jcballesteros** [opencitydata/sector-publico-subvenciones-ayudas#18]
Necesitamos una propiedad para utilizar el skos "http://vocab.linkeddata.es/datosabiertos/kos/sector-publico/subvencion/tipo-instrumento"

De momento nosotros la hemos generado como:  essubv:tipoInstrumento

Por el momento las URIs del SKOS no son derreferenciables.

**Comment by ocorcho** [comment]
Propiedad añadida en el commit 08a5f23e998ca16339a0c9df6b1cdef3f24f8db4

**Comment by ocorcho** [comment]
Se cierra este issue y se abre un nuevo issue en el repositorio correspondiente para el tratamiento de las URIs de-referenciables de SKOS. https://github.com/opencitydata/listas-codigos-skos/issues/8
